apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: hoh-gitops
  namespace: hoh-subscriptions
spec:
    type: Git
    pathname: https://github.com/stolostron/hub-of-hubs-gitops