apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: hoh-gitops-k8s-resources-subscription
  namespace: default
  annotations:
    apps.open-cluster-management.io/git-path: examples/git-objects/k8s-resources
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: hoh-subscriptions/hoh-gitops
  name: hub-of-hubs-gitops
  placement:
    local: true