---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hoh-gitops-pv
  labels:
    type: local
spec:
  storageClassName: hoh-gitops
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/hub-of-hubs-subscription-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hoh-gitops-pv-claim
  namespace: open-cluster-management
spec:
  storageClassName: hoh-gitops
  resources:
    requests:
      storage: 7G
  accessModes:
    - ReadWriteMany