---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hoh-gitops-pv
spec:
  storageClassName: hoh-gitops
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/hub-of-hubs-subscription-storage"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-10-0-136-193
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hoh-gitops-pv-claim
  namespace: open-cluster-management
spec:
  storageClassName: hoh-gitops
  resources:
    requests:
      storage: 10G
  accessModes:
    - ReadWriteOnce